import { create } from 'zustand';
import { FishSpecies } from '../types';

interface FishStoreState {
  allSpecies: FishSpecies[];
  setAllSpecies: (species: FishSpecies[]) => void;
  getSpeciesById: (id: string) => FishSpecies | undefined;
}

// 1세대(출시) 10종 — 도감 1페이지
const GEN1_FISH_SPECIES: FishSpecies[] = [
  {
    id: 'clownfish',
    name: '클라운피시',
    scientificName: 'Amphiprioninae',
    rarity: 'common',
    habitat: '열대 산호초',
    description: '흰 줄무늬가 특징인 산호초의 인기 어종. 말미잘과 공생 관계를 맺는다.',
    modelPath: 'models/fish/clownfish.glb',
    thumbnailPath: 'images/fish/clownfish.png',
    baseGrowthTime: 300,
  },
  {
    id: 'guppy',
    name: '구피',
    scientificName: 'Poecilia reticulata',
    rarity: 'common',
    habitat: '담수',
    description: '화려한 지느러미를 가진 소형 열대어. 번식력이 강하고 키우기 쉽다.',
    modelPath: 'models/fish/guppy.glb',
    thumbnailPath: 'images/fish/guppy.png',
    baseGrowthTime: 240,
  },
  {
    id: 'goldfish',
    name: '금붕어',
    scientificName: 'Carassius auratus',
    rarity: 'common',
    habitat: '담수',
    description: '관상어의 대명사. 다양한 색상과 형태가 있으며 수명이 길다.',
    modelPath: 'models/fish/goldfish.glb',
    thumbnailPath: 'images/fish/goldfish.png',
    baseGrowthTime: 360,
  },
  {
    id: 'seahorse',
    name: '해마',
    scientificName: 'Hippocampus',
    rarity: 'common',
    habitat: '열대 해역',
    description: '수직으로 헤엄치는 독특한 어류. 수컷이 새끼를 낳는 것으로 유명하다.',
    modelPath: 'models/fish/seahorse.glb',
    thumbnailPath: 'images/fish/seahorse.png',
    baseGrowthTime: 420,
  },
  {
    id: 'zebrafish',
    name: '제브라피시',
    scientificName: 'Danio rerio',
    rarity: 'common',
    habitat: '담수',
    description: '줄무늬 패턴이 아름다운 소형 어류. 과학 연구에도 널리 사용된다.',
    modelPath: 'models/fish/zebrafish.glb',
    thumbnailPath: 'images/fish/zebrafish.png',
    baseGrowthTime: 200,
  },
  {
    id: 'betta',
    name: '베타',
    scientificName: 'Betta splendens',
    rarity: 'rare',
    habitat: '담수',
    description: '화려한 지느러미와 공격적인 성격으로 유명한 싸움꼬리. 아름다운 색상이 특징.',
    modelPath: 'models/fish/betta.glb',
    thumbnailPath: 'images/fish/betta.png',
    baseGrowthTime: 600,
  },
  {
    id: 'angelfish',
    name: '엔젤피시',
    scientificName: 'Pterophyllum scalare',
    rarity: 'rare',
    habitat: '아마존',
    description: '삼각형의 독특한 체형을 가진 우아한 어류. 아마존 강이 원산지.',
    modelPath: 'models/fish/angelfish.glb',
    thumbnailPath: 'images/fish/angelfish.png',
    baseGrowthTime: 720,
  },
  {
    id: 'mandarin_fish',
    name: '만다린피시',
    scientificName: 'Synchiropus splendidus',
    rarity: 'rare',
    habitat: '산호초',
    description: '세계에서 가장 아름다운 물고기 중 하나. 화려한 색상의 패턴이 특징.',
    modelPath: 'models/fish/mandarin.glb',
    thumbnailPath: 'images/fish/mandarin_fish.png',
    baseGrowthTime: 900,
  },
  {
    id: 'leafy_sea_dragon',
    name: '바다용',
    scientificName: 'Phycodurus eques',
    rarity: 'epic',
    habitat: '온대 해역',
    description: '잎사귀처럼 생긴 위장 돌기가 있는 신비로운 어류. 해마의 친척.',
    modelPath: 'models/fish/sea_dragon.glb',
    thumbnailPath: 'images/fish/leafy_sea_dragon.png',
    baseGrowthTime: 1800,
  },
  {
    id: 'coelacanth',
    name: '실러캔스',
    scientificName: 'Latimeria chalumnae',
    rarity: 'legendary',
    habitat: '심해',
    description: '3억 6천만 년 전부터 살아온 살아있는 화석. 현존하는 가장 신비로운 물고기.',
    modelPath: 'models/fish/coelacanth.glb',
    thumbnailPath: 'images/fish/coelacanth.png',
    baseGrowthTime: 7200,
  },
];

// 2세대(v1.1.0) 10종 — 도감 2페이지. 1세대 도감 완성 시 해금 (constants isGen2Unlocked)
const GEN2_FISH_SPECIES: FishSpecies[] = [
  {
    id: 'neon_tetra',
    name: '네온테트라',
    scientificName: 'Paracheirodon innesi',
    rarity: 'common',
    habitat: '아마존 담수',
    description: '네온처럼 빛나는 파란 줄과 붉은 꼬리가 매력적인 소형어. 무리 지어 헤엄치는 모습이 아름답다.',
    modelPath: 'models/fish/neon_tetra.glb',
    thumbnailPath: 'images/fish/neon_tetra.png',
    baseGrowthTime: 200,
  },
  {
    id: 'butterflyfish',
    name: '나비고기',
    scientificName: 'Chaetodontidae',
    rarity: 'common',
    habitat: '산호초',
    description: '나비처럼 나풀거리며 헤엄치는 노란 물고기. 꼬리 쪽 가짜 눈으로 천적을 속인다.',
    modelPath: 'models/fish/butterflyfish.glb',
    thumbnailPath: 'images/fish/butterflyfish.png',
    baseGrowthTime: 300,
  },
  {
    id: 'pufferfish',
    name: '복어',
    scientificName: 'Tetraodontidae',
    rarity: 'common',
    habitat: '연안',
    description: '위험을 느끼면 몸을 풍선처럼 부풀리는 물고기. 동글동글한 몸매가 사랑스럽다.',
    modelPath: 'models/fish/pufferfish.glb',
    thumbnailPath: 'images/fish/pufferfish.png',
    baseGrowthTime: 360,
  },
  {
    id: 'blue_tang',
    name: '블루탱',
    scientificName: 'Paracanthurus hepatus',
    rarity: 'rare',
    habitat: '산호초',
    description: '선명한 파란 몸과 노란 꼬리의 대비가 아름다운 어종. 영화 주인공으로도 유명하다.',
    modelPath: 'models/fish/blue_tang.glb',
    thumbnailPath: 'images/fish/blue_tang.png',
    baseGrowthTime: 600,
  },
  {
    id: 'discus',
    name: '디스커스',
    scientificName: 'Symphysodon',
    rarity: 'rare',
    habitat: '아마존',
    description: '원반 모양의 몸에 물결무늬가 흐르는 열대어의 제왕. 부모가 새끼에게 몸의 점액을 먹인다.',
    modelPath: 'models/fish/discus.glb',
    thumbnailPath: 'images/fish/discus.png',
    baseGrowthTime: 720,
  },
  {
    id: 'koi',
    name: '코이',
    scientificName: 'Cyprinus rubrofuscus',
    rarity: 'rare',
    habitat: '담수',
    description: '홍백의 무늬가 한 마리마다 다른 비단잉어. 환경에 따라 크기가 달라지는 것으로 유명하다.',
    modelPath: 'models/fish/koi.glb',
    thumbnailPath: 'images/fish/koi.png',
    baseGrowthTime: 900,
  },
  {
    id: 'lionfish',
    name: '라이언피시',
    scientificName: 'Pterois volitans',
    rarity: 'epic',
    habitat: '산호초',
    description: '사자 갈기처럼 펼쳐진 독가시 지느러미를 가진 화려한 포식자. 아름답지만 만지면 위험하다.',
    modelPath: 'models/fish/lionfish.glb',
    thumbnailPath: 'images/fish/lionfish.png',
    baseGrowthTime: 1800,
  },
  {
    id: 'anglerfish',
    name: '초롱아귀',
    scientificName: 'Melanocetus johnsonii',
    rarity: 'epic',
    habitat: '심해',
    description: '이마의 발광 미끼로 먹잇감을 유인하는 심해의 사냥꾼. 어둠 속에서 초롱불처럼 빛난다.',
    modelPath: 'models/fish/anglerfish.glb',
    thumbnailPath: 'images/fish/anglerfish.png',
    baseGrowthTime: 2400,
  },
  {
    id: 'arowana',
    name: '아로와나',
    scientificName: 'Scleropages formosus',
    rarity: 'legendary',
    habitat: '동남아 담수',
    description: '용을 닮은 금빛 비늘과 수염 때문에 행운을 부르는 물고기로 불린다. 1억 년을 살아온 고대 어종.',
    modelPath: 'models/fish/arowana.glb',
    thumbnailPath: 'images/fish/arowana.png',
    baseGrowthTime: 7200,
  },
  {
    id: 'oarfish',
    name: '산갈치',
    scientificName: 'Regalecus glesne',
    rarity: 'legendary',
    habitat: '심해',
    description: '붉은 관을 쓴 은빛 리본 같은 심해어. 깊은 바다의 전령이라 불리는 신비로운 존재.',
    modelPath: 'models/fish/oarfish.glb',
    thumbnailPath: 'images/fish/oarfish.png',
    baseGrowthTime: 7200,
  },
];

/** 도감 페이지 구성: [0]=1세대, [1]=2세대 */
export const FISH_SPECIES_PAGES: FishSpecies[][] = [GEN1_FISH_SPECIES, GEN2_FISH_SPECIES];

export const useFishStore = create<FishStoreState>((set, get) => ({
  allSpecies: [...GEN1_FISH_SPECIES, ...GEN2_FISH_SPECIES],

  setAllSpecies: species => set({ allSpecies: species }),

  getSpeciesById: id => get().allSpecies.find(s => s.id === id),
}));
