import { create } from 'zustand';
import { FishSpecies } from '../types';

interface FishStoreState {
  allSpecies: FishSpecies[];
  setAllSpecies: (species: FishSpecies[]) => void;
  getSpeciesById: (id: string) => FishSpecies | undefined;
}

// MVP 10종 fish species 데이터
const MVP_FISH_SPECIES: FishSpecies[] = [
  {
    id: 'clownfish',
    name: '클라운피시',
    scientificName: 'Amphiprioninae',
    rarity: 'common',
    habitat: '열대 산호초',
    description: '흰 줄무늬가 특징인 산호초의 인기 어종. 말미잘과 공생 관계를 맺는다.',
    modelPath: 'models/fish/clownfish.glb',
    thumbnailPath: 'images/fish/clownfish.png',
    baseGrowthTime: 300,
  },
  {
    id: 'guppy',
    name: '구피',
    scientificName: 'Poecilia reticulata',
    rarity: 'common',
    habitat: '담수',
    description: '화려한 지느러미를 가진 소형 열대어. 번식력이 강하고 키우기 쉽다.',
    modelPath: 'models/fish/guppy.glb',
    thumbnailPath: 'images/fish/guppy.png',
    baseGrowthTime: 240,
  },
  {
    id: 'goldfish',
    name: '금붕어',
    scientificName: 'Carassius auratus',
    rarity: 'common',
    habitat: '담수',
    description: '관상어의 대명사. 다양한 색상과 형태가 있으며 수명이 길다.',
    modelPath: 'models/fish/goldfish.glb',
    thumbnailPath: 'images/fish/goldfish.png',
    baseGrowthTime: 360,
  },
  {
    id: 'seahorse',
    name: '해마',
    scientificName: 'Hippocampus',
    rarity: 'common',
    habitat: '열대 해역',
    description: '수직으로 헤엄치는 독특한 어류. 수컷이 새끼를 낳는 것으로 유명하다.',
    modelPath: 'models/fish/seahorse.glb',
    thumbnailPath: 'images/fish/seahorse.png',
    baseGrowthTime: 420,
  },
  {
    id: 'zebrafish',
    name: '제브라피시',
    scientificName: 'Danio rerio',
    rarity: 'common',
    habitat: '담수',
    description: '줄무늬 패턴이 아름다운 소형 어류. 과학 연구에도 널리 사용된다.',
    modelPath: 'models/fish/zebrafish.glb',
    thumbnailPath: 'images/fish/zebrafish.png',
    baseGrowthTime: 200,
  },
  {
    id: 'betta',
    name: '베타',
    scientificName: 'Betta splendens',
    rarity: 'rare',
    habitat: '담수',
    description: '화려한 지느러미와 공격적인 성격으로 유명한 싸움꼬리. 아름다운 색상이 특징.',
    modelPath: 'models/fish/betta.glb',
    thumbnailPath: 'images/fish/betta.png',
    baseGrowthTime: 600,
  },
  {
    id: 'angelfish',
    name: '엔젤피시',
    scientificName: 'Pterophyllum scalare',
    rarity: 'rare',
    habitat: '아마존',
    description: '삼각형의 독특한 체형을 가진 우아한 어류. 아마존 강이 원산지.',
    modelPath: 'models/fish/angelfish.glb',
    thumbnailPath: 'images/fish/angelfish.png',
    baseGrowthTime: 720,
  },
  {
    id: 'mandarin_fish',
    name: '만다린피시',
    scientificName: 'Synchiropus splendidus',
    rarity: 'rare',
    habitat: '산호초',
    description: '세계에서 가장 아름다운 물고기 중 하나. 화려한 색상의 패턴이 특징.',
    modelPath: 'models/fish/mandarin.glb',
    thumbnailPath: 'images/fish/mandarin_fish.png',
    baseGrowthTime: 900,
  },
  {
    id: 'leafy_sea_dragon',
    name: '바다용',
    scientificName: 'Phycodurus eques',
    rarity: 'epic',
    habitat: '온대 해역',
    description: '잎사귀처럼 생긴 위장 돌기가 있는 신비로운 어류. 해마의 친척.',
    modelPath: 'models/fish/sea_dragon.glb',
    thumbnailPath: 'images/fish/leafy_sea_dragon.png',
    baseGrowthTime: 1800,
  },
  {
    id: 'coelacanth',
    name: '실러캔스',
    scientificName: 'Latimeria chalumnae',
    rarity: 'legendary',
    habitat: '심해',
    description: '3억 6천만 년 전부터 살아온 살아있는 화석. 현존하는 가장 신비로운 물고기.',
    modelPath: 'models/fish/coelacanth.glb',
    thumbnailPath: 'images/fish/coelacanth.png',
    baseGrowthTime: 7200,
  },

  // ==================== 귀여운 마스코트 확장 10종 ====================
  {
    id: 'pufferfish',
    name: '복어',
    scientificName: 'Tetraodontidae',
    rarity: 'common',
    habitat: '열대·온대 바다',
    description: '위협을 느끼면 몸을 풍선처럼 부풀리는 물고기. 동글동글한 몸매가 매력적이다.',
    modelPath: 'models/fish/pufferfish.glb',
    thumbnailPath: 'images/fish/pufferfish.png',
    baseGrowthTime: 300,
  },
  {
    id: 'starfish',
    name: '불가사리',
    scientificName: 'Asteroidea',
    rarity: 'common',
    habitat: '조간대 바위',
    description: '팔이 다섯 개인 별 모양의 극피동물. 팔이 잘려도 다시 자라난다.',
    modelPath: 'models/fish/starfish.glb',
    thumbnailPath: 'images/fish/starfish.png',
    baseGrowthTime: 240,
  },
  {
    id: 'crab',
    name: '게',
    scientificName: 'Brachyura',
    rarity: 'common',
    habitat: '갯벌·연안',
    description: '옆으로 걷는 갑각류. 커다란 집게발로 먹이를 잡고 자신을 지킨다.',
    modelPath: 'models/fish/crab.glb',
    thumbnailPath: 'images/fish/crab.png',
    baseGrowthTime: 300,
  },
  {
    id: 'jellyfish',
    name: '해파리',
    scientificName: 'Scyphozoa',
    rarity: 'rare',
    habitat: '전 세계 바다',
    description: '투명한 우산 모양 몸으로 물속을 하늘하늘 떠다니는 신비로운 생물.',
    modelPath: 'models/fish/jellyfish.glb',
    thumbnailPath: 'images/fish/jellyfish.png',
    baseGrowthTime: 600,
  },
  {
    id: 'octopus',
    name: '문어',
    scientificName: 'Octopoda',
    rarity: 'rare',
    habitat: '암초 바다',
    description: '여덟 개의 다리와 뛰어난 지능을 가진 연체동물. 몸 색을 자유자재로 바꾼다.',
    modelPath: 'models/fish/octopus.glb',
    thumbnailPath: 'images/fish/octopus.png',
    baseGrowthTime: 780,
  },
  {
    id: 'sea_turtle',
    name: '바다거북',
    scientificName: 'Chelonioidea',
    rarity: 'rare',
    habitat: '열대 바다',
    description: '단단한 등딱지를 가진 온순한 파충류. 수백 년을 살기도 하는 바다의 장수 동물.',
    modelPath: 'models/fish/sea_turtle.glb',
    thumbnailPath: 'images/fish/sea_turtle.png',
    baseGrowthTime: 900,
  },
  {
    id: 'axolotl',
    name: '아홀로틀',
    scientificName: 'Ambystoma mexicanum',
    rarity: 'epic',
    habitat: '멕시코 담수호',
    description: '영원히 어린 모습으로 사는 우파루파. 잃어버린 신체를 스스로 재생하는 능력이 있다.',
    modelPath: 'models/fish/axolotl.glb',
    thumbnailPath: 'images/fish/axolotl.png',
    baseGrowthTime: 1800,
  },
  {
    id: 'manta_ray',
    name: '쥐가오리',
    scientificName: 'Mobula birostris',
    rarity: 'epic',
    habitat: '열대 외양',
    description: '거대한 날개를 펼치고 바닷속을 나는 듯 헤엄치는 가오리. 온순한 성격이다.',
    modelPath: 'models/fish/manta_ray.glb',
    thumbnailPath: 'images/fish/manta_ray.png',
    baseGrowthTime: 2400,
  },
  {
    id: 'penguin',
    name: '펭귄',
    scientificName: 'Spheniscidae',
    rarity: 'epic',
    habitat: '남극·한류 해역',
    description: '날개로 물속을 나는 새. 뒤뚱거리는 걸음과 턱시도 무늬가 사랑스럽다.',
    modelPath: 'models/fish/penguin.glb',
    thumbnailPath: 'images/fish/penguin.png',
    baseGrowthTime: 2000,
  },
  {
    id: 'narwhal',
    name: '일각고래',
    scientificName: 'Monodon monoceros',
    rarity: 'legendary',
    habitat: '북극해',
    description: "이마에 긴 뿔이 달린 '바다의 유니콘'. 사실 이 뿔은 엄청나게 길게 자란 앞니다.",
    modelPath: 'models/fish/narwhal.glb',
    thumbnailPath: 'images/fish/narwhal.png',
    baseGrowthTime: 7200,
  },
];

export const useFishStore = create<FishStoreState>((set, get) => ({
  allSpecies: MVP_FISH_SPECIES,

  setAllSpecies: species => set({ allSpecies: species }),

  getSpeciesById: id => get().allSpecies.find(s => s.id === id),
}));
